package gotopark.buster.lottogen.Module

import android.util.Log
import gotopark.buster.lottogen.R
import java.util.*

/**
 * Created by buster on 17. 9. 14.
 * 남아프리리카 로또 방법
 * 1.Lotto : 6 numbers from 1 to 52
 * 2.Lotto Plus : choose 6 numbers from 1 to 52
 * 3.Lotto Plus 2 : 6 numbers from 1 to 52
 * 4.Powerball :  5 numbers from 1 to 45 on and 1 extra number from 1 to 20
 * 5.Powerball Plus :  choose 5 numbers from 1 to 45 on and 1 extra number from 1 to 20
 */

class randomNum {
    val rand = Random()

    fun lotArray(input1: Int, input2: Int): IntArray {

        val num = IntArray(input1)
        var xnum: Int
        var icount: Int
        var j: Int
        //         로또 번호 발생 및  중복 제거

        icount = 0
        while (icount < input1) {
            xnum = rand.nextInt(input2) + 1
            num[icount] = xnum
            j = 0
            while (j < icount) {
                if (num[icount] == num[j]) {
                    xnum = rand.nextInt(input2) + 1
                    num[icount] = xnum
                    icount = icount - 1
                    break
                }
                j++
            }
            icount++
        }
        //   오름 차순으로  정렬 및 딜레이 시간
        Arrays.sort(num)
        return num

    }
    fun frontSay(): Int {
        val sayword = intArrayOf(
                R.string.frontword1,
                R.string.frontword2,
                R.string.frontword3,
                R.string.frontword4,
                R.string.frontword5,
                R.string.frontword6,
                R.string.frontword7,
                R.string.frontword8,
                R.string.frontword9,
                R.string.frontword10,
                R.string.frontword11,
                R.string.frontword12,
                R.string.frontword13,
                R.string.frontword14,
                R.string.frontword15,
                R.string.frontword16,
                R.string.frontword17,
                R.string.frontword18,
                R.string.frontword19,
                R.string.frontword20,
                R.string.frontword21,
                R.string.frontword22,
                R.string.frontword23,
                R.string.frontword24,
                R.string.frontword25,
                R.string.frontword26,
                R.string.frontword27,
                R.string.frontword28,
                R.string.frontword29,
                R.string.frontword30,
                R.string.frontword31,
                R.string.frontword32,
                R.string.frontword33,
                R.string.frontword34,
                R.string.frontword35,
                R.string.frontword36,
                R.string.frontword37,
                R.string.frontword38,
                R.string.frontword39,
                R.string.frontword40,
                R.string.frontword41,
                R.string.frontword42,
                R.string.frontword43,
                R.string.frontword44,
                R.string.frontword45,
                R.string.frontword46,
                R.string.frontword47,
                R.string.frontword48,
                R.string.frontword49,
                R.string.frontword50,
                R.string.frontword51,
                R.string.frontword52,
                R.string.frontword53,
                R.string.frontword54,
                R.string.frontword55,
                R.string.frontword56,
                R.string.frontword57,
                R.string.frontword58,
                R.string.frontword59,
                R.string.frontword60,
                R.string.frontword61,
                R.string.frontword62,
                R.string.frontword63,
                R.string.frontword64,
                R.string.frontword65,
                R.string.frontword66,
                R.string.frontword67,
                R.string.frontword68,
                R.string.frontword69,
                R.string.frontword70,
                R.string.frontword71,
                R.string.frontword72,
                R.string.frontword73,
                R.string.frontword74,
                R.string.frontword75,
                R.string.frontword76,
                R.string.frontword77,
                R.string.frontword78,
                R.string.frontword79,
                R.string.frontword80,
                R.string.frontword81,
                R.string.frontword82,
                R.string.frontword83,
                R.string.frontword84,
                R.string.frontword85,
                R.string.frontword86,
                R.string.frontword87,
                R.string.frontword88,
                R.string.frontword89,
                R.string.frontword90,
                R.string.frontword91,
                R.string.frontword92,
                R.string.frontword93,
                R.string.frontword94,
                R.string.frontword95,
                R.string.frontword96,
                R.string.frontword97,
                R.string.frontword98,
                R.string.frontword99,
                R.string.frontword100,
                R.string.frontword101,
                R.string.frontword102,
                R.string.frontword103,
                R.string.frontword104,
                R.string.frontword105,
                R.string.frontword106,
                R.string.frontword107,
                R.string.frontword108,
                R.string.frontword109,
                R.string.frontword110,
                R.string.frontword111,
                R.string.frontword112,
                R.string.frontword113,
                R.string.frontword114,
                R.string.frontword115,
                R.string.frontword116,
                R.string.frontword117,
                R.string.frontword118,
                R.string.frontword119,
                R.string.frontword120,
                R.string.frontword121,
                R.string.frontword122,
                R.string.frontword123,
                R.string.frontword124,
                R.string.frontword125,
                R.string.frontword126,
                R.string.frontword127,
                R.string.frontword128,
                R.string.frontword129,
                R.string.frontword130,
                R.string.frontword131,
                R.string.frontword132,
                R.string.frontword133,
                R.string.frontword134,
                R.string.frontword135,
                R.string.frontword136,
                R.string.frontword137,
                R.string.frontword138,
                R.string.frontword139,
                R.string.frontword140,
                R.string.frontword141,
                R.string.frontword142,
                R.string.frontword143,
                R.string.frontword144,
                R.string.frontword145,
                R.string.frontword146,
                R.string.frontword147,
                R.string.frontword148,
                R.string.frontword149,
                R.string.frontword150,
                R.string.frontword151,
                R.string.frontword152,
                R.string.frontword153,
                R.string.frontword154,
                R.string.frontword155,
                R.string.frontword156,
                R.string.frontword157,
                R.string.frontword158,
                R.string.frontword159,
                R.string.frontword160,
                R.string.frontword161,
                R.string.frontword162,
                R.string.frontword163,
                R.string.frontword164,
                R.string.frontword165,
                R.string.frontword166,
                R.string.frontword167,
                R.string.frontword168,
                R.string.frontword169,
                R.string.frontword170,
                R.string.frontword171,
                R.string.frontword172,
                R.string.frontword173,
                R.string.frontword174,
                R.string.frontword175,
                R.string.frontword176,
                R.string.frontword177,
                R.string.frontword178,
                R.string.frontword179,
                R.string.frontword180,
                R.string.frontword181,
                R.string.frontword182,
                R.string.frontword183,
                R.string.frontword184,
                R.string.frontword185,
                R.string.frontword186,
                R.string.frontword187,
                R.string.frontword188,
                R.string.frontword189,
                R.string.frontword190,
                R.string.frontword191,
                R.string.frontword192,
                R.string.frontword193,
                R.string.frontword194,
                R.string.frontword195,
                R.string.frontword196,
                R.string.frontword197,
                R.string.frontword198,
                R.string.frontword199,
                R.string.frontword200,
                R.string.frontword201,
                R.string.frontword202,
                R.string.frontword203,
                R.string.frontword204,
                R.string.frontword205,
                R.string.frontword206,
                R.string.frontword207,
                R.string.frontword208,
                R.string.frontword209,
                R.string.frontword210,
                R.string.frontword211,
                R.string.frontword212,
                R.string.frontword213,
                R.string.frontword214,
                R.string.frontword215,
                R.string.frontword216,
                R.string.frontword217,
                R.string.frontword218,
                R.string.frontword219,
                R.string.frontword220,
                R.string.frontword221,
                R.string.frontword222,
                R.string.frontword223,
                R.string.frontword224,
                R.string.frontword225,
                R.string.frontword226,
                R.string.frontword227,
                R.string.frontword228,
                R.string.frontword229,
                R.string.frontword230,
                R.string.frontword231,
                R.string.frontword232,
                R.string.frontword233,
                R.string.frontword234,
                R.string.frontword235,
                R.string.frontword236,
                R.string.frontword237,
                R.string.frontword238,
                R.string.frontword239,
                R.string.frontword240,
                R.string.frontword241,
                R.string.frontword242,
                R.string.frontword243,
                R.string.frontword244,
                R.string.frontword245,
                R.string.frontword246,
                R.string.frontword247,
                R.string.frontword248,
                R.string.frontword249,
                R.string.frontword250,
                R.string.frontword251,
                R.string.frontword252,
                R.string.frontword253,
                R.string.frontword254,
                R.string.frontword255,
                R.string.frontword256,
                R.string.frontword257,
                R.string.frontword258,
                R.string.frontword259,
                R.string.frontword260,
                R.string.frontword261,
                R.string.frontword262,
                R.string.frontword263,
                R.string.frontword264,
                R.string.frontword265,
                R.string.frontword266,
                R.string.frontword267,
                R.string.frontword268,
                R.string.frontword269,
                R.string.frontword270,
                R.string.frontword271,
                R.string.frontword272,
                R.string.frontword273,
                R.string.frontword274,
                R.string.frontword275,
                R.string.frontword276,
                R.string.frontword277,
                R.string.frontword278,
                R.string.frontword279,
                R.string.frontword280,
                R.string.frontword281,
                R.string.frontword282,
                R.string.frontword283,
                R.string.frontword284,
                R.string.frontword285,
                R.string.frontword286,
                R.string.frontword287,
                R.string.frontword288,
                R.string.frontword289,
                R.string.frontword290,
                R.string.frontword291,
                R.string.frontword292,
                R.string.frontword293,
                R.string.frontword294,
                R.string.frontword295,
                R.string.frontword296,
                R.string.frontword297,
                R.string.frontword298,
                R.string.frontword299);

        val wrdMax = 298
        val i = rand.nextInt(wrdMax) + 1

        Log.e("=========", Arrays.toString(sayword))

        return sayword[i]
    }
}